### ISSUE TITLE
DSA 1.1.2 Arrangement, Rearrangement in Arrays (Reversal, rerrange zeros/+ve/-ve)

### ISSUE THREAD

**Issue by pjdurden** [girlscript/winter-of-contributing#110]
## Description
Standard rearrangement problems like reversing, rearrange positive and negative, and move zeros to end.

## Task
- [ ] Documentation
- [ ] Audio
- [ ] Video

## Note
- While requesting the issue to be assigned, please mention your **NAME & BATCH NUMBER**.
- Kindly refer to [Issue Guidelines](https://github.com/girlscript/winter-of-contributing/blob/DSA/DSA/CONTRIBUTING.md#issues).
- In case you see that the issue has already been assigned, try to request for a different task within the same issue.
- Changes should be made inside the ````DSA/directory```` & ````DSA```` branch.
- Name of the file should be same as the issue.
- This issue is only for 'GWOC' contributors of 'DSA' Domain.

**Comment by NiharikaSngh** [comment]
I wish to resolve this issue.

**Comment by srikars-1** [comment]
I would like to work on this issue

**Comment by Akshat-2002-coder** [comment]
i would like to work on it.

**Comment by priyanshu688** [comment]
@VikasPandey121 Sir can I work on this issue??

**Comment by jaissumi1402** [comment]
Please assign this issue to me, I would like to work on this issue under GWOC

**Comment by Subhradeep10** [comment]
@jaissumi1402 Already assign to someone else. Don't Worry many issue will come up

**Comment by jaissumi1402** [comment]
@Subhradeep10 okay sir

**Comment by Subhradeep10** [comment]
@NiharikaSngh Any updates?

**Comment by NiharikaSngh** [comment]
@Subhradeep10 Sir, can you guide me how to proceed further?

**Comment by Subhradeep10** [comment]
@NiharikaSngh  Well contruibuting is easy I will say that later or you can talk about that in Discord also, First say do you have prerequisite knowledge on Arrangement, Rearrangement in Arrays?

- If No, First read about the Arrays from GFG or W3Schools and gain proper knowledge from it.

- If Yes, Go and prepare a Documentation on Readme (.md) extension.Basic Introduction about the topic , Some code example and line by line explaination of the code. Similar topic regarding that , and the make a video / audio with mp4 extension. Don't do blindly copy paste otherwise we have to gave you plagiarism and the issue will be solved by someone else.

And if you face any issue. You can ask my directly in the discord

All the best🚀

**Comment by EktaAgrawal** [comment]
Hello sir, I have a keen interest in this and wanted to contribute. kindly assign me

**Comment by russapal** [comment]
Hello Sir, I would like to contribute in this issue.

**Comment by Subhradeep10** [comment]
Someone is already assigned for this issue, if after creating pull request if you guys face any issue with her code, you can again open the issue and I will assign it to you

**Comment by VikasPandey121** [comment]
> @VikasPandey121 Sir can I work on this issue??

LGTM, please ask the DSA supervisor for assigning this issue to you.

**Comment by NiharikaSngh** [comment]
@Ash-KODES I am sorry but how could you do this ? I was assigned this issue on the very first day !!

**Comment by Subhradeep10** [comment]
@NiharikaSngh Chill This task is assigned to you only, and @Ash-KODES Stop doing this, otherwise I have to complain to higher authority
