### ISSUE TITLE
Stl : Vector in C++

### ISSUE THREAD

**Issue by Akriti-Choudhary** [girlscript/winter-of-contributing#2076]
### Description

Documentation on Vector(stl)

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by vasu-1** [comment]
Hey @geetika005  and @akratikushwah this issue is already assigned to @Akriti-Choudhary so you cannot reassigned to yourself. kindly make another issue but .
### note that there should not be any duplicate issue 👍 
### you can not work on the issue which is already assigned to someone else 👍 
I hope it will make sense to both of you !

**Comment by vasu-1** [comment]
@Ajaycodex see above instruction !

**Comment by akratikushwah** [comment]
> Hey @geetika005  and @akratikushwah this issue is already assigned to @Akriti-Choudhary so you cannot reassigned to yourself. kindly make another issue but .
> ### note that there should not be any duplicate issue 👍 
> ### you can not work on the issue which is already assigned to someone else 👍 
> I hope it will make sense to both of you !

Okay I will create my own issue and will work on it
