### ISSUE TITLE
Program Execution in JavaScript

### ISSUE THREAD

**Issue by aakankshabhende** [girlscript/winter-of-contributing#259]
Will document the execution context, its phases and call stack
Can I work on this issue?

**Comment by paramsiddharth** [comment]
Hey Aakansha! I think your issue was missed due to improper formatting. Sorry about that, please try to use the format specified in the contribution guide here: https://github.com/girlscript/winter-of-contributing/blob/Javascript/JavaScript/CONTRIBUTING.md

Please look for another issue or create your own! Thank you so much for the contribution!

P. S. Are you joining our weekly acknowledgement sessions on Discord?
